# Application name
spring.application.name=toeic-backend

# Datasource PostgreSQL (kh?p v?i docker-compose: user=user, password=12122004, db=toeic_db)
spring.datasource.url=jdbc:postgresql://localhost:5432/toeic_db
spring.datasource.username=user
spring.datasource.password=12122004
spring.datasource.hikari.maximum-pool-size=10
google.client.id=64251716543-8uu8euqmt4gm0hsnhufp9vj3oojtdndb.apps.googleusercontent.com

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=20

# Flyway (t?t vì b?n không mu?n dùng)
spring.flyway.enabled=false

# Redis (k?t n?i t?i container Redis)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Mail (SMTP Gmail) ? dùng bi?n môi tr??ng
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
# JWT
jwt.secret=${JWT_SECRET:mySuperSecretKeyForJWT12345678901234567890}
jwt.expiration=900000
jwt.refreshExpiration=604800000

# Custom TOEIC SRS settings
toeic.srs.base-interval-hours=1
toeic.srs.max-interval-days=365

# Server
server.port=8080
server.error.include-message=always

# Logging
logging.level.com.toeic=DEBUG